### ISSUE TITLE
Loading geoip db into memory on every request

### ISSUE THREAD

**Issue by srgkm** [koslib/django-traffic#1]
Hi there,

Most probably it is better to move this part out of process_request method.

https://github.com/koslibpro/django-traffic/blob/master/django-traffic/middleware.py#L93

**Comment by koslib** [comment]
@srgkm hello! Yes, you're right actually, I will have this fixed in the next version! Will ping you here as well ;) 
oh and of course you're more than welcome to create a PR for this @srgkm :D

**Comment by koslib** [comment]
@srgkm I think it's much better now, have a look! Thanks!
